# Generated by Django 5.0.1 on 2024-08-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_acer_profile_address_profile_assigned_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.CharField(blank=True, max_length=100)),
                ('batch_type', models.CharField(blank=True, max_length=100)),
                ('order_no', models.CharField(blank=True, max_length=100)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('borrower_name_1', models.CharField(blank=True, max_length=255)),
                ('borrower_name_2', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('organization_date', models.DateField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=100)),
                ('assigned_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('processor_name', models.CharField(blank=True, max_length=100)),
                ('typing', models.CharField(blank=True, max_length=100)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('order', models.CharField(blank=True, max_length=100)),
                ('acer', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
