# Generated by Django 5.0.4 on 2024-08-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_businessdetails_delete_businessdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
