# Generated by Django 5.0.4 on 2024-08-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_businessdetails_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='sl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sl',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
