# Generated by Django 5.0.4 on 2024-08-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_businessdetails_sl_alter_profile_sl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sl',
            field=models.IntegerField(unique=True),
        ),
    ]
