# Generated by Django 5.0.4 on 2024-08-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_profile_sl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='acer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='assigned_on',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='batch_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='borrower_name_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='borrower_name_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='completed_on',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='order',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='organization_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='processor_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='product',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='received_on',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sl',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='typing',
        ),
    ]
