# Generated by Django 5.0.4 on 2024-08-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_client_client_id_remove_client_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdetails',
            old_name='country',
            new_name='county',
        ),
    ]
