# Generated by Django 5.0.4 on 2024-08-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_country_businessdetails_county'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessdetails',
            options={'ordering': ['received_on'], 'verbose_name': 'Business Detail', 'verbose_name_plural': 'Business Details'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['first_name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
