# Generated by Django 5.0.4 on 2024-08-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_businessdetails_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdetails',
            old_name='acer',
            new_name='Qcer',
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='assigned_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=90, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='organization_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='received_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
