# Generated by Django 5.0.4 on 2024-08-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_acer_businessdetails_qcer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdetails',
            old_name='organization_date',
            new_name='Origination_date',
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('Clarification', 'Clarification')], default='pending', max_length=20),
        ),
    ]
